services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapi
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db_script:/docker-entrypoint-initdb.d

  myapi:
    container_name: myapi_java
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - ./target/myappi-0.0.1-SNAPSHOT.jar:/app/myappi-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/product-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - postgres